[package]
name = "ttt_client"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "ttt_client"
path = "src/manual.rs"

[[bin]]
name = "ttt_bot"
path = "src/bot.rs"

[dependencies]
